l_polish:
 # BASE/MISC
 BPM_VALUE_BASE:0 "Base value"

 BPM_VALUE_FROM_NO_TECH_MASS_COMMS:0 "no Mass Communication [Concept('concept_technology', 'Tech')]"

 # LAW/INSTITUTION
 BPM_VALUE_FROM_LAW_MONARCHY:0 "[Concept('concept_law', 'Law')] [GetLawType('law_monarchy').GetName]"
 BPM_VALUE_FROM_LAW_TRADITIONALISM:0 "[Concept('concept_law', 'Law')] [GetLawType('law_traditionalism').GetName]"
 BPM_VALUE_FROM_LAW_LAISSEZ_FAIRE:0 "[Concept('concept_law', 'Law')] [GetLawType('law_laissez_faire').GetName]"
 BPM_VALUE_FROM_LAW_INTERVENTIONISM:0 "[Concept('concept_law', 'Law')] [GetLawType('law_interventionism').GetName]"
 BPM_VALUE_FROM_LAW_PEASANT_LEVIES:0 "[Concept('concept_law', 'Law')] [GetLawType('law_peasant_levies').GetName]"
 BPM_VALUE_FROM_LAW_SERFDOM:0 "[Concept('concept_law', 'Law')] [GetLawType('law_serfdom').GetName]"
 BPM_VALUE_FROM_LAW_TENANT_FARMERS:0 "[Concept('concept_law', 'Law')] [GetLawType('law_tenant_farmers').GetName]"
 BPM_VALUE_FROM_LAW_COMMERCIALIZED_AGRICULTURE:0 "[Concept('concept_law', 'Law')] [GetLawType('law_commercialized_agriculture').GetName]"
 BPM_VALUE_FROM_LAW_ISOLATIONISM:0 "[Concept('concept_law', 'Law')] [GetLawType('law_isolationism').GetName]"
 BPM_VALUE_FROM_LAW_UNREGULATED_WORK_TIME:0 "[Concept('concept_law', 'Law')] [GetLawType('law_unregulated_work_time').GetName]"
 BPM_VALUE_FROM_LAW_NO_WORKERS_RIGHTS:0 "[Concept('concept_law', 'Law')] [GetLawType('law_no_workers_rights').GetName]"
 BPM_VALUE_FROM_LAW_NO_WELFARE:0 "[Concept('concept_law', 'Law')] [GetLawType('law_no_social_security').GetName]"
 BPM_VALUE_FROM_LAW_POOR_LAWS:0 "[Concept('concept_law', 'Law')] [GetLawType('law_poor_laws').GetName]"
 BPM_VALUE_FROM_LAW_NO_ELECTIONS:0 "[Concept('concept_law', 'Law')] No [Concept('concept_election', 'Elections')]"
 BPM_VALUE_FROM_LAW_NO_FULL_DEMOCRACY:0 "[Concept('concept_law', 'Law')] No [GetLawType('law_universal_suffrage').GetName] with full Suffrage investment"
 BPM_VALUE_FROM_LAW_OUTLAWED_DISSENT:0 "[Concept('concept_law', 'Law')] [GetLawType('law_outlawed_dissent').GetName]"
 BPM_VALUE_FROM_LAW_SOCIALIST_BAN:0 "[Concept('concept_law', 'Law')] [GetLawType('law_party_anti_socialist').GetName]"
 BPM_VALUE_FROM_LAW_CENSORSHIP:0 "[Concept('concept_law', 'Law')] [GetLawType('law_censorship').GetName]"
 BPM_VALUE_FROM_LAW_PROTECTED_SPEECH:0 "[Concept('concept_law', 'Law')] [GetLawType('law_protected_speech').GetName]"
 BPM_VALUE_FROM_LAW_ANARCHY:0 "[Concept('concept_law', 'Law')] [GetLawType('law_anarchy').GetName]"
 BPM_VALUE_FROM_LAW_AD_HOC_CENTRALIZATION:0 "[Concept('concept_law', 'Law')] [GetLawType('law_ad_hoc_centralization').GetName]"
 BPM_VALUE_FROM_LAW_STATE_RELIGION:0 "[Concept('concept_law', 'Law')] [GetLawType('law_state_religion').GetName]"
 BPM_VALUE_FROM_LAW_STATE_ATHEISM:0 "[Concept('concept_law', 'Law')] [GetLawType('law_state_atheism').GetName]"
 BPM_VALUE_FROM_LAW_NO_MULTICULTURALISM:0 "[Concept('concept_law', 'Law')] No [GetLawType('law_multicultural').GetName]"
 BPM_VALUE_FROM_INSTITUTION_LOCAL_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_local_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_dedicated_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_MILITARIZED_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_militarized_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_ELECTED_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_elected_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_NATIONAL_GUARD:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_national_guard').GetName]"
 BPM_VALUE_FROM_INSTITUTION_SECRET_POLICE:0 "[Concept('concept_institution', 'Institution')] investment in [GetLawType('law_secret_police').GetName]"
 BPM_VALUE_FROM_INSTITUTION_GUARANTEED_LIBERTIES:0 "[Concept('concept_institution', 'Institution')] investment with [GetLawType('law_guaranteed_liberties').GetName]"
 BPM_VALUE_FROM_INSTITUTION_SUFFRAGE:0 "[Concept('concept_institution', 'Institution')] investment in [GetInstitutionType('institution_suffrage').GetName]"

 # CURRENT STATUS
 BPM_VALUE_FROM_RADICALS:0 "[Concept('concept_radical', 'Radicals')]"
 BPM_VALUE_FROM_LOYALISTS:0 "[Concept('concept_loyalist', 'Loyalists')]"
 BPM_VALUE_FROM_WAR:0 "[Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_WAR_HIGH_SUPPORT:0 "High [Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_WAR_MEDIUM_SUPPORT:0 "Medium [Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_WAR_LOW_SUPPORT:0 "Low [Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_WAR_VERY_LOW_SUPPORT:0 "Very Low [Concept('concept_war_support', 'War Support')]"
 BPM_VALUE_FROM_REVOLUTION:0 "Ongoing [Concept('concept_revolution', 'Revolution')]"
 BPM_VALUE_FROM_INSURRECTION:0 "Insurrectionary [Concept('concept_interest_group', 'Interest Groups')]"
 BPM_VALUE_FROM_ELECTION:0 "Ongoing [Concept('concept_election', 'Election')]"
 BPM_VALUE_FROM_LOW_LEGITIMACY:0 "Low (below 30) [Concept('concept_legitimacy', 'Legitimacy')]"
 BPM_VALUE_FROM_VERY_LOW_LEGITIMACY:0 "Very low (below 10) [Concept('concept_legitimacy', 'Legitimacy')]"
 BPM_VALUE_FROM_ENTRENCHED_INTEREST_GROUPS:0 "Every year the current ruling [Concept('concept_interest_group', 'Interest Groups')] spent in government"
 BPM_VALUE_FROM_RIGIDITY:0 "[Concept('concept_bpm_political_stability', '$concept_bpm_political_stability$')]"

 # INTEREST GROUPS & CHARACTERS
 BPM_VALUE_POWERFUL_ANARCHISTS:0 "Anarchists Powerful"
 BPM_VALUE_BOLSTERED_ANARCHISTS:0 "Anarchists Bolstered"
 BPM_VALUE_ANARCHIST_AGITATORS:0 "Anarchist [Concept('concept_agitator', 'Agitators')]"
 BPM_VALUE_FROM_MONARCH_POPULARITY:0 "[Concept('concept_ruler', 'Monarch')] [Concept('concept_popularity', 'Popularity')] ([GetPlayer.GetRuler.GetFullName])"
 BPM_VALUE_FROM_N_LEADER_AND_AGITATORS:0 "[Concept('concept_popularity', 'Popularity')] of [Concept('concept_leader', 'Leader')] and [Concept('concept_agitator', 'Agitators')] of"
 BPM_VALUE_FROM_CONSERVATIVE_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_conservatives',GetPlayer).GetName]"
 BPM_VALUE_FROM_REACTIONARY_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_reactionaries',GetPlayer).GetName]"
 BPM_VALUE_FROM_LIBERAL_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_liberals',GetPlayer).GetName]"
 BPM_VALUE_FROM_RADICAL_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_radicals',GetPlayer).GetName]"
 BPM_VALUE_FROM_SOCIALIST_LEADER_AND_AGITATORS:0 "$BPM_VALUE_FROM_N_LEADER_AND_AGITATORS$ [GetInterestGroupVariant('ig_socialists',GetPlayer).GetName]"

 # JOURNAL SPECIFIC
 BPM_VALUE_FROM_JOURNAL_PROGRESS:0 "Journal Entry Progress"
 BPM_VALUE_JOURNAL_DURATION:0 "Journal Entry Duration"
 BPM_VALUE_POTD_ENDED_IN_GP:0 "Propaganda of the Deed has been resolved in a [Concept('concept_great_power', 'Great Power')]"

 # WAR
 BPM_STABILITY_FROM_WAR_BASE:0 "#gold Ongoing War#! Base Value"
 BPM_STABILITY_FROM_WAR_OCCUPATION:0 "#gold Ongoing War#! Enemy Occupation"
 BPM_STABILITY_FROM_WAR_CASUALTIES:0 "#gold Ongoing War#! Casualties"